# Factorización de Cholesky

In [ ]:
import numpy as np

A = np.array([[1,-2,2],[-2,5,-3],[2,-3,6]])
L = np.linalg.cholesky(A)
print(L)

[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 2.  1.  1.]]


## Mostrar L y L traspuesta mediante factorización de Cholesky

In [ ]:
import numpy as np

In [ ]:
#Ingresar una matriz cualquiera
m = int(input('Digite el número de ecuaciones e incógnitas a resolver: '))
n = m
p = False
matriz = np.empty((m, n))
vectorb = np.empty(m)

# Llenaremos la matriz con elementos numéricos
for i in range(m):
    vectorb[i] = float(input(f'Ingrese el valor b({i + 1}): '))
    for j in range(n):
        matriz[i, j] = float(input(f'Ingrese el elemento en la posición ({i + 1}, {j + 1}): '))

# Verificar simetría
def es_simetrica(matriz):
    return np.allclose(matriz, matriz.T)

# Calcular los valores propios
valores_propios = np.linalg.eigvals(matriz)

# Verificar definida positiva
def es_definida_positiva(valores_propios):
    return np.all(valores_propios > 0)

# Verificar si se puede aplicar la factorización de Cholesky
def se_puede_aplicar_cholesky(matriz):
    return es_simetrica(matriz) and es_definida_positiva(np.linalg.eigvals(matriz))

if se_puede_aplicar_cholesky(matriz):
    print("Se puede aplicar la factorización de Cholesky.")
    p = True
else:
    print("No se puede aplicar la factorización de Cholesky.")
    p = False

Se puede aplicar la factorización de Cholesky.


In [ ]:
if p == True:
    L = np.zeros((m,n))
    for i in range(m):
        for j in range(i+1):
            if j == i:
                suma_cuadrados = np.sum(L[j][:j]**2)
                L[j, j] = np.sqrt(matriz[j, j] - suma_cuadrados)
            else:
                suma_productos = np.sum(L[i][:j] * L[j][:j])
                L[i, j] = (matriz[i, j] - suma_productos) / L[j, j]
    print('La matriz resultante es:')            
    print(L)
    
    # Traspuesta de L
    L_transpuesta = L.T
    print('La traspuesta de la matriz resultante es:')
    print(L_transpuesta)
else:
    print('No se puede aplicar la factorización de Cholesky para la matriz dada.')

La matriz resultante es:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 2.  1.  1.]]
La traspuesta de la matriz resultante es:
[[ 1. -2.  2.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]]


## Matriz tridiagonal

In [ ]:
def tridiagonal(alfa, beta, gamma):
    n = len(beta)
    matriz = np.zeros((n, n))
    np.fill_diagonal(matriz, alfa)
    np.fill_diagonal(matriz[1:], beta)
    np.fill_diagonal(matriz[:, 1:], gamma)
    return matriz

def cholesky_test(matriz):
    L = np.zeros_like(matriz)
    n = len(matriz)
    for i in range(n):
        for j in range(i + 1):
            if j == i:
                suma_cuadrados = np.sum(L[j][:j]**2)
                L[j, j] = np.sqrt(matriz[j, j] - suma_cuadrados)
            else:
                suma_productos = np.sum(L[i][:j] * L[j][:j])
                L[i, j] = (matriz[i, j] - suma_productos) / L[j, j]
    return L

# Parámetros alfa, beta y gamma
alfa = 2
beta = [1, 1, 1, 1, 1]  # Longitud de beta determina el tamaño de la matriz
gamma = 2

# Crear matriz tridiagonal
matriz_tridiagonal = tridiagonal(alfa, beta, gamma)

# Probar la factorización de Cholesky
L = cholesky_test(matriz_tridiagonal)
print("Matriz tridiagonal:")
print(matriz_tridiagonal)
print("Factorización de Cholesky (matriz L):")
print(L)

Matriz tridiagonal:
[[2. 2. 0. 0. 0.]
 [1. 2. 2. 0. 0.]
 [0. 1. 2. 2. 0.]
 [0. 0. 1. 2. 2.]
 [0. 0. 0. 1. 2.]]
Factorización de Cholesky (matriz L):
[[1.41421356 0.         0.         0.         0.        ]
 [0.70710678 1.22474487 0.         0.         0.        ]
 [0.         0.81649658 1.15470054 0.         0.        ]
 [0.         0.         0.8660254  1.11803399 0.        ]
 [0.         0.         0.         0.89442719 1.09544512]]


# Método de Jacobi

In [ ]:
import numpy as np
def jacobi(A,b,x0,max_iter,tol):
  n = len(A)
  ID = np.zeros((n,n))
  I = np.zeros((n,n))
  for i in range(n):
    ID[i,i] = 1/A[i,i]
    I[i,i] = 1
  #
  B = I - ID@A
  c = ID@b
  xk = B@x0 + c
  dif = np.linalg.norm(xk-x0)
  m = 0
  while m<=max_iter and dif>tol:
    x0 = xk
    xk = B@xk + c
    dif = np.linalg.norm(xk-x0)
    m += 1
  return xk, n

# EJEMPLO

A = np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0], [0,0,-1,2,-1], [0,0,0,-1,2]])
b = np.array([[1],[1],[1],[1],[1]])
sol = jacobi(A,b,b,20,1e-6)
sol

(array([[2.42960811],
        [3.87329459],
        [4.35921621],
        [3.87329459],
        [2.42960811]]),
 5)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=1d0b360a-30c4-4b6e-85d4-4074d6b2a469' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>