# Tarea

1. Implementar el método SOR  para A = tridiag(-1, -2, -1)

In [ ]:
```
    Ejemplo
    def SOR(A, b, x_0, n_max, tol, w)
    función w_opt
    n = 10
    np.linalg.pignals
```

SyntaxError: invalid syntax (3787984978.py, line 1)

## Matriz tridiagonal

In [ ]:
import numpy as np

def tridiagonal(alfa, beta, gamma):
    n = len(beta)
    matriz = np.zeros((n, n))
    np.fill_diagonal(matriz, alfa)
    np.fill_diagonal(matriz[1:], beta)
    np.fill_diagonal(matriz[:, 1:], gamma)
    return matriz

def cholesky_test(matriz):
    L = np.zeros_like(matriz)
    n = len(matriz)
    for i in range(n):
        for j in range(i + 1):
            if j == i:
                suma_cuadrados = np.sum(L[j][:j]**2)
                L[j, j] = np.sqrt(matriz[j, j] - suma_cuadrados)
            else:
                suma_productos = np.sum(L[i][:j] * L[j][:j])
                L[i, j] = (matriz[i, j] - suma_productos) / L[j, j]
    return L

# Parámetros alfa, beta y gamma
alfa = 2
beta = [1, 1, 1, 1]  # Longitud de beta determina el tamaño de la matriz
gamma = 2

# Crear matriz tridiagonal
matriz_tridiagonal = tridiagonal(alfa, beta, gamma)

# Probar la factorización de Cholesky
L = cholesky_test(matriz_tridiagonal)
print("Matriz tridiagonal:")
print(matriz_tridiagonal)
print("Factorización de Cholesky (matriz L):")
print(L)

Matriz tridiagonal:
[[2. 2. 0. 0.]
 [1. 2. 2. 0.]
 [0. 1. 2. 2.]
 [0. 0. 1. 2.]]
Factorización de Cholesky (matriz L):
[[1.41421356 0.         0.         0.        ]
 [0.70710678 1.22474487 0.         0.        ]
 [0.         0.81649658 1.15470054 0.        ]
 [0.         0.         0.8660254  1.11803399]]


## Jacobi

In [ ]:
import numpy as np
def jacobi(A,b,x0,max_iter,tol):
  n = len(A)
  ID = np.zeros((n,n))
  I = np.zeros((n,n))
  for i in range(n):
    ID[i,i] = 1/A[i,i]
    I[i,i] = 1
  #
  B = I - ID@A
  c = ID@b
  xk = B@x0 + c
  dif = np.linalg.norm(xk-x0)
  m = 0
  while m<=max_iter and dif>tol:
    x0 = xk
    xk = B@xk + c
    dif = np.linalg.norm(xk-x0)
    m += 1
  return xk, n

# EJEMPLO

A = np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0], [0,0,-1,2,-1], [0,0,0,-1,2]])
b = np.array([[1],[1],[1],[1],[1]])
sol = jacobi(A,b,b,20,1e-6)
sol

(array([[2.42960811],
        [3.87329459],
        [4.35921621],
        [3.87329459],
        [2.42960811]]),
 5)

# Implementación SOR

El método SOR se implementa mediante la siguiente representación matemáticos con matriz de paramétro w

> wAx = wb

> ((D-wE)-(wF + (1-w)D))x = wb

## Implementación con matriz tridiagona (-1,2,-1)

In [ ]:
import numpy as np

def sor(A, b, omega, x0, tol=1e-6, max_iter=1000):
    """
    Implementación del método SOR (Successive Over-Relaxation).

    Parámetros:
    A: numpy.array
        Matriz de coeficientes del sistema lineal.
    b: numpy.array
        Vector de términos independientes.
    omega: float
        Factor de relajación (0 < omega < 2).
    x0: numpy.array
        Vector inicial de la solución.
    tol: float
        Tolerancia: criterio de convergencia.
    max_iter: int
        Número máximo de iteraciones permitidas.

    Devuelve:
    x: numpy.array
        Vector solución aproximada.
    iterations: int
        Número de iteraciones realizadas.
    """
    n = len(b)
    x = x0.copy()
    iterations = 0
    error = tol + 1
    eigenvalues = np.linalg.eigvals(A)
    rho = max(abs(eigenvalues))
    omega = 2 / (1 + np.sqrt(1 - rho**2))

    while error > tol and iterations < max_iter:
        x_old = x.copy()

        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i, j] * x[j]
            x[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sigma)

        error = np.linalg.norm(x - x_old)
        iterations += 1

    return x, iterations

# Ejemplo de uso
# A = np.array([[4, -1, 0, 0],
#               [-1, 4, -1, 0],
#               [0, -1, 4, -1],
#               [0, 0, -1, 4]])

# b = np.array([5, 5, 0, 5])

x0 = np.zeros_like(b)
omega = 1.2
tol = 1e-6
max_iter = 1000

solucion, num_iteraciones = sor(A, b, omega, x0, 1e-6, 1000)

print("Solución aproximada:", solucion)
print("Número de iteraciones:", num_iteraciones)


NameError: name 'b' is not defined

### Implementación con ejemplo 

In [ ]:
import numpy as np

def sor(A, b, omega, x0, tol, max_iter):
    """
    Implementación del método SOR (Successive Over-Relaxation).

    Parámetros:
    A: numpy.array
        Matriz de coeficientes del sistema lineal.
    b: numpy.array
        Vector de términos independientes.
    omega: float
        Factor de relajación (0 < omega < 2).
    x0: numpy.array
        Vector inicial de la solución.
    tol: float
        Tolerancia: criterio de convergencia.
    max_iter: int
        Número máximo de iteraciones permitidas.

    Devuelve:
    x: numpy.array
        Vector solución aproximada.
    iterations: int
        Número de iteraciones realizadas.
    """
    n = len(b)
    x = x0.copy()
    iterations = 0
    error = tol + 1

    while error > tol and iterations < max_iter:
        x_old = x.copy()

        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i, j] * x[j]
            x[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sigma)

        error = np.linalg.norm(x - x_old)
        iterations += 1

    return x, iterations

# Definir matriz A tridiagonal
n = 5
A = np.zeros((n, n))
for i in range(n):
    A[i, i] = -2
    if i > 0:
        A[i, i - 1] = -1
    if i < n - 1:
        A[i, i + 1] = -1

# Definir vector b
b = np.ones(n)

# Definir otros parámetros
x0 = np.zeros_like(b)
omega = 1.2
tol = 1e-6
max_iter = 10

# Resolver usando el método SOR
solucion, num_iteraciones = sor(A, b, omega, x0, tol, max_iter)

# Imprimir resultados
print("Solución aproximada:", solucion)
print("Número de iteraciones:", num_iteraciones)


Solución aproximada: [-0.49673689 -0.00443214 -0.49598634 -0.00272567 -0.49876593]
Número de iteraciones: 10


### Implementación paso a paso

In [ ]:
import numpy as np

# Se realiza inicilmente Jacobi a la matriz que se ingrese
def jacobi(A,b,x0,max_iter,tol):
  n = len(A)
  ID = np.zeros((n,n))
  I = np.zeros((n,n))
  for i in range(n):
    ID[i,i] = 1/A[i,i]
    I[i,i] = 1
  #
  B = I - ID@A
  c = ID@b
  xk = B@x0 + c
  dif = np.linalg.norm(xk-x0)
  m = 0
  while m<=max_iter and dif>tol:
    x0 = xk
    xk = B@xk + c
    dif = np.linalg.norm(xk-x0)
    m += 1
  return xk, n

# EJEMPLO

# A = np.array([[2, -1, 0, 0, 0],
#               [-1, 2, -1, 0, 0],
#               [0, -1, 2, -1, 0],
#               [0, 0, -1, 2, -1],
#               [0, 0, 0, -1, 2]])
# b = np.array([[6], [25], [-11], [15], [4]])
sol = jacobi(A,b,b,max_iter,tol)
print(sol)


(array([[21.8333329 ],
       [37.66666633],
       [28.49999914],
       [30.333333  ],
       [17.16666624]]), 5)


In [ ]:
import numpy as np


import numpy as np

# Función para calcular omega óptima
def calculate_optimal_omega(A):
    eigenvalues = np.linalg.eigvals(A)
    rho = max(abs(eigenvalues))
    omega = 2 / (1 + np.sqrt(1 - rho**2))
    return omega

# Luego descomponemos el SOR
def sor_decomposition(A, omega):
    n = A.shape[0]
    D = np.diag(np.diag(A))
    E = np.tril(A, k=-1)
    F = np.triu(A, k=1)
    
    D_minus_wE = D - omega * E
    wF_plus_D_minus_wE = omega * F + (1 - omega) * D
    
    D_minus_wE_inv = np.linalg.inv(D_minus_wE)
    
    return D_minus_wE_inv, wF_plus_D_minus_wE

# Función SOR
def sor(A, b, omega, x0, tol=1e-6, max_iter=1000):
    n = len(b)
    x = x0.copy()
    iterations = 0
    error = tol + 1
    
    # Descomposición SOR de la matriz A
    D_minus_wE_inv, wF_plus_D_minus_wE = sor_decomposition(A, omega)
    
    while error > tol and iterations < max_iter:
        x_old = x.copy()
        
        # Iteración SOR
        x = np.dot(D_minus_wE_inv, np.dot(wF_plus_D_minus_wE, x) + np.dot(D_minus_wE_inv, b))
        
        error = np.linalg.norm(x - x_old)
        iterations += 1
    
    return x, iterations

# Ejemplo de uso
A = np.array([[6, 1, 1, 1, 1],
              [1, 8, 1, 1, 1],
              [1, 1, 10, 1, 1],
              [1, 1, 1, 9, 1],
              [1, 1, 1, 1, 7]])
b = np.array([10, 20, 30, 40, 50])
x0 = np.zeros_like(b)
omega = calculate_optimal_omega(A)  # Calcula el omega óptimo
tol = 1e-6
max_iter = 1000

solucion, num_iteraciones = sor(A, b, omega, x0, tol, max_iter)

print("Solución aproximada:", solucion)
print("Número de iteraciones:", num_iteraciones)


Solución aproximada: [nan nan nan nan nan]
Número de iteraciones: 1
/tmp/ipykernel_40/1031814827.py:10: RuntimeWarning: invalid value encountered in sqrt
  omega = 2 / (1 + np.sqrt(1 - rho**2))


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=1d0b360a-30c4-4b6e-85d4-4074d6b2a469' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>